# Use root/example as user/password credentials

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO-DB-ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO-DB-ROOT-PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOEXPRESS-ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOEXPRESS-ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGOEXPRESS-URL}
      ME_CONFIG_BASICAUTH: false
